{
 "title": "dbscale",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "BackendServerConnection",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dbscale_status{status = \"BackendServerConnection\"}"
    }
   ]
  },
  {
   "title": "NumbersTmpTablePool",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dbscale_status{status = \"NumbersTmpTablePool\"}"
    }
   ]
  },
  {
   "title": "RunningTims(s)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dbscale_status{status = \"RunningTime(s)\"}"
    }
   ]
  },
  {
   "title": "Show_Queries",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dbscale_status{status = \"Slow_Queries\"}"
    }
   ]
  },
  {
   "title": "TPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dbscale_status{status= \"TPS\"}"
    }
   ]
  },
  {
   "title": "TPSCountingTime",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dbscale_status{status = \"TPSCountingTime\"}"
    }
   ]
  },
  {
   "title": "Times3PhaseTxnOnlyOneSimpleTxn",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dbscale_status{status = \"Times3PhaseTxnOnlyOneSimpleTxn\"}"
    }
   ]
  },
  {
   "title": "Times3PhaseTxnReal3fTxn",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dbscale_status{status = \"Times3PhaseTxnReal3fTxn\"}"
    }
   ]
  },
  {
   "title": "Times3PhaseTxnXATxn",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dbscale_status{status = \"Times3PhaseTxnXATxn\"}"
    }
   ]
  },
  {
   "title": "TimesAllReadSourceOfReplicationUnAvailable",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dbscale_status{status = \"TimesAllReadSourceOfReplicationUnAvailable\"  }"
    }
   ]
  },
  {
   "title": "TimesCallStmtExecuteOnDBscaleSide",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dbscale_status{status = \"TimesCallStmtExecuteOnDBscaleSide\"}"
    }
   ]
  },
  {
   "title": "TimesChangeMaster",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dbscale_status{status = \"TimesChangeMaster\"}"
    }
   ]
  },
  {
   "title": "TimesClientBrokenNotUsingQuit",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dbscale_status{status = \"TimesClientBrokenNotUsingQuit\"}"
    }
   ]
  },
  {
   "title": "TimesCreateNewTmpTables",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dbscale_status{status = \"TimesCreateNewTmpTables\"}"
    }
   ]
  },
  {
   "title": "TimesCrossNodeJoin",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dbscale_status{status = \"TimesCrossNodeJoin\"}"
    }
   ]
  },
  {
   "title": "TimesCrossNodeJoinOrTableSubQueryMoveDataMoreThanOnce",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dbscale_status{status = \"TimesCrossNodeJoinOrTableSubQueryMoveDataMoreThanOnce\"}"
    }
   ]
  },
  {
   "title": "TimesDBScaleFailFlushConfToZoo",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dbscale_status{status = \"TimesDBScaleFailFlushConfToZoo\"}"
    }
   ]
  },
  {
   "title": "TimesDBScaleLatestImportantWarning",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dbscale_status{status = \"TimesDBScaleLatestImportantWarning\"}"
    }
   ]
  },
  {
   "title": "TimesDBScalePoolReachMaxWater",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dbscale_status{status = \"TimesDBScalePoolReachMaxWater\"}"
    }
   ]
  },
  {
   "title": "TimesDelete",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dbscale_status{status = \"TimesDelete\"}"
    }
   ]
  },
  {
   "title": "TimesErrorGeneratedByDBscale",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dbscale_status{status = \"TimesErrorGeneratedByDBscale\"}"
    }
   ]
  },
  {
   "title": "TimesErrorPacketFromServer",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 80 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dbscale_status{status = \"TimesErrorPacketFromServer\"}"
    }
   ]
  },
  {
   "title": "TimesExecutionPlanTouchAllPartition",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 88 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dbscale_status{status = \"TimesExecutionPlanTouchAllPartition\"}"
    }
   ]
  },
  {
   "title": "TimesExecutionPlanTouchOnePartition",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 88 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dbscale_status{status = \"TimesExecutionPlanTouchOnePartition\"}"
    }
   ]
  },
  {
   "title": "TimesExecutionPlanTouchTwoPartition",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 96 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dbscale_status{status = \"TimesExecutionPlanTouchTwoPartition\"}"
    }
   ]
  },
  {
   "title": "TimesFailStoreMetadata",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 96 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dbscale_status{status = \"TimesFailStoreMetadata\"}"
    }
   ]
  },
  {
   "title": "TimesInsert",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 104 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dbscale_status{status = \"TimesInsert\"}"
    }
   ]
  },
  {
   "title": "TimesInsertSelect",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 104 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dbscale_status{status = \"TimesInsertSelect\"}"
    }
   ]
  },
  {
   "title": "TimesPartialParsingRelatedToPartitionTable",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 112 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dbscale_status{status = \"TimesPartialParsingRelatedToPartitionTable\"}"
    }
   ]
  },
  {
   "title": "TimesPartialParsingWithoutTableName",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 112 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dbscale_status{status = \"TimesPartialParsingWithoutTableName\"}"
    }
   ]
  },
  {
   "title": "TimesReplicationBroken",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 120 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dbscale_status{status = \"TimesReplicationBroken\"}"
    }
   ]
  },
  {
   "title": "TimesSelect",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 120 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dbscale_status{status = \"TimesSelect\"}"
    }
   ]
  },
  {
   "title": "TimesServerDown",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 128 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dbscale_status{status = \"TimesServerDown\"}"
    }
   ]
  },
  {
   "title": "TimesStmtRecordAsSlowQueryByDBscale",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 128 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dbscale_status{status = \"TimesStmtRecordAsSlowQueryByDBscale\"}"
    }
   ]
  },
  {
   "title": "TimesTxn",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 136 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dbscale_status{status = \"TimesTxn\"}"
    }
   ]
  },
  {
   "title": "TimesUpdate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 136 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dbscale_status{status = \"TimesUpdate\"}"
    }
   ]
  },
  {
   "title": "TimesUseDuplicateTable",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 144 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dbscale_status{status =\"TimesUseDuplicateTable\"}"
    }
   ]
  },
  {
   "title": "TimesUseTmpTable",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 144 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dbscale_status{status = \"TimesUseTmpTable\"}"
    }
   ]
  },
  {
   "title": "TimesWarningsCount",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 152 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dbscale_status{status = \"TimesWarningsCount\"}"
    }
   ]
  },
  {
   "title": "TimesXAOptimizeOnlyAffectOneServer",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 152 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dbscale_status{status = \"TimesXAOptimizeOnlyAffectOneServer\"}"
    }
   ]
  },
  {
   "title": "TimesXAOptimizeReadOnlyStmt",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 160 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dbscale_status{status = \"TimesXAOptimizeReadOnlyStmt\"}"
    }
   ]
  },
  {
   "title": "TimesXAUNRelayFailTransaction",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 160 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dbscale_status{status = \"TimesXAUNRelayFailTransaction\"}"
    }
   ]
  }
 ]
}